workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        # هنا نقوم بتوجيه الـ Java مباشرة إلى إصدار 17 ليتوافق مع مشروعك
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local properties and environment file
        script: |
          # إنشاء ملف .env لتجنب مشاكل الـ Secrets Plugin
          touch .env
          echo "PROJECT_PROPERTY=example_value" >> .env
          
      - name: Grant execute permission for gradlew
        script: |
          chmod +x gradlew

      - name: Build Android APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk