workflows:
  android-build:
    name: Build Android AAB
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local properties and environment file
        script: |
          touch .env
          echo "PROJECT_PROPERTY=example_value" >> .env
          
      - name: Grant execute permission for gradlew
        script: |
          chmod +x gradlew

      - name: Build Android App Bundle (AAB)
        script: |
          # تم تغيير الأمر هنا ليقوم ببناء ملف الـ AAB بدلاً من الـ APK
          ./gradlew bundleRelease

    artifacts:
      # تم تعديل المسار والامتداد هنا ليلتقط ملف الـ .aab المستخرج
      - app/build/outputs/bundle/release/*.aab